name: "SSH Setup"
description: "Install SSH keys and setup known_hosts"

runs:
  using: "composite"
  steps:
    - name: Install SSH keys
      shell: bash
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
